resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/316c854d1d3089f480708ad5cd5ecf8a74423ddd/snapshot.yaml
compiler: ghc-8.6.5

allow-newer: true

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
#   subdirs:
#   - auto-update
#   - wai
packages:
- .

flags:
  # Bundle VRF crypto in libsodium and do not rely on an external fork to have it.
  # This still requires the host system to have the 'standard' libsodium installed.
  cardano-crypto-praos:
    external-libsodium-vrf: false

extra-deps:

  - binary-0.8.7.0
  - bimap-0.4.0
  - brick-0.47.1
  - config-ini-0.2.4.0
  - containers-0.5.11.0
  - data-clist-0.1.2.3
  - ekg-prometheus-adapter-0.1.0.4
  - esqueleto-3.2.2
  - generic-monoid-0.1.0.0
  - libsystemd-journal-1.4.4
  - network-3.1.1.1
  - snap-core-1.0.4.1
  - snap-server-1.1.1.1
  - persistent-2.10.5.1
  - persistent-postgresql-2.10.1.2
  - persistent-template-2.8.2.3
  - prometheus-2.1.2
  - pvss-0.2.0
  - tasty-hedgehog-1.0.0.2
  - text-zipper-0.10.1
  - time-units-1.0.0
  - word-wrap-0.4.1
  - transformers-except-0.1.1
  - text-ansi-0.1.0
  - Diff-0.4.0
  - katip-0.8.3.0
  - moo-1.2
  - gray-code-0.3.1
  - Unique-0.4.7.6
  - statistics-linreg-0.3
  - socks-0.6.1
  - servant-0.17
  - servant-server-0.17
  - connection-0.3.1
  - http-api-data-0.4.1.1
  - time-compat-1.9.2.2
  - quiet-0.2
  - quickcheck-state-machine-0.6.0

  - git: https://github.com/input-output-hk/cardano-db-sync
    commit: 5fa05200ea928e37a26f061e02ac44feda234135
    subdirs:
      - cardano-db
      - cardano-db-sync
      - cardano-db-sync-extended

  - git: https://github.com/input-output-hk/cardano-shell
    commit: b3231f7f3b8b6d07fef08f8cc41aa804524f94c2
    subdirs:
      - cardano-shell

  - git: https://github.com/input-output-hk/cardano-crypto
    commit: 2547ad1e80aeabca2899951601079408becbc92c

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 316c854d1d3089f480708ad5cd5ecf8a74423ddd
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: efa4b5ecd7f0a13124616b12679cd42517cd905a
    subdirs:
      - contra-tracer
      - iohk-monitoring
      - plugins/backend-aggregation
      - plugins/backend-ekg
      - plugins/backend-monitoring
      - plugins/backend-trace-forwarder
      - plugins/scribe-systemd
      - tracer-transformers

  - git: https://github.com/input-output-hk/cardano-base
    commit: c454b6e791ee2fe84508b4d5ed2c4dedafb7dce4
    subdirs:
      - binary
      - cardano-crypto-praos
      - binary/test
      - cardano-crypto-class
      - slotting

  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 4e65f6e3f966659b69865fd6bcfe9caf3008b820
    subdirs:
      - byron/crypto
      - byron/crypto/test
      - byron/chain/executable-spec
      - byron/ledger/executable-spec
      - byron/ledger/impl
      - byron/ledger/impl/test
      - semantics/executable-spec
      - semantics/small-steps-test
      - shelley/chain-and-ledger/dependencies/non-integer
      - shelley/chain-and-ledger/executable-spec
      - shelley/chain-and-ledger/executable-spec/test

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 11e5609e01f4703870e88b2712e2c14da0338b65
    subdirs:
      - cardano-client
      - io-sim
      - io-sim-classes
      - network-mux
      - ouroboros-network
      - ouroboros-network-framework
      - Win32-network
      - ouroboros-consensus
      - ouroboros-consensus-byron
      - ouroboros-consensus-byronspec
      - ouroboros-consensus-shelley
      - ouroboros-consensus-cardano
      - typed-protocols
      - typed-protocols-examples
      - ouroboros-network-testing
      - ouroboros-consensus/ouroboros-consensus-mock
      - ouroboros-consensus/ouroboros-consensus-test-infra

  - git: https://github.com/input-output-hk/cardano-node
    commit: 8c72fc00cb75b7e7a2c9423ba50c639f6236c88b
    subdirs:
      - cardano-config

nix:
  shell-file: nix/stack-shell.nix
