resolver: https://raw.githubusercontent.com/input-output-hk/cardano-haskell/master/snapshots/cardano-1.25.1.yaml
compiler: ghc-8.6.5

#allow-newer: true

packages:
- smash
- smash-servant-types

flags:
  # Bundle VRF crypto in libsodium and do not rely on an external fork to have it.
  # This still requires the host system to have the 'standard' libsodium installed.
  cardano-crypto-praos:
    external-libsodium-vrf: false

ghc-options:
  smash:                    -Wall -Werror -fno-warn-redundant-constraints
  #smash-servant-types:      -Wall -Werror -fno-warn-redundant-constraints

# Generate files required by Weeder.
# See https://github.com/ndmitchell/weeder/issues/53
ghc-options: {"$locals": -ddump-to-file -ddump-hi}

extra-deps:
  - persistent-2.11.0.1
  - persistent-postgresql-2.11.0.0
  - persistent-template-2.9.1.0

  - esqueleto-3.4.0.1

  # Compiler error 'System.Metrics.Prometheus.Http.Scrape (serveMetricsT)'
  - prometheus-2.2.2

  - git: https://github.com/input-output-hk/cardano-db-sync
    commit: d5aa846e0751227aa6461084d6ea0567535f752e
    subdirs:
      - cardano-sync
      - cardano-db
      - cardano-db-sync

nix:
  shell-file: nix/stack-shell.nix
