resolver: https://raw.githubusercontent.com/input-output-hk/cardano-haskell/5ed4af4df2a609361260f159cd0e47e1c4073e2c/snapshots/cardano-1.24.2.yaml
compiler: ghc-8.6.5

#allow-newer: true

packages:
- smash
- smash-servant-types

flags:
  # Bundle VRF crypto in libsodium and do not rely on an external fork to have it.
  # This still requires the host system to have the 'standard' libsodium installed.
  cardano-crypto-praos:
    external-libsodium-vrf: false

ghc-options:
  smash:                    -Wall -Werror -fwarn-redundant-constraints
  #smash-servant-types:      -Wall -Werror -fwarn-redundant-constraints

extra-deps:
  - persistent-2.11.0.1
  - persistent-postgresql-2.11.0.0
  - persistent-template-2.9.1.0

  - esqueleto-3.4.0.1

  # Compiler error 'System.Metrics.Prometheus.Http.Scrape (serveMetricsT)'
  - prometheus-2.2.2

  - git: https://github.com/input-output-hk/cardano-db-sync
    commit: 3cf868ec8c06265e4b670ac737af640d716e5ef7
    subdirs:
      - cardano-db
      - cardano-db-sync
      - cardano-db-sync-extended

nix:
  shell-file: nix/stack-shell.nix
